spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACTHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  zipkin:
      base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8765

feign:
  hystrix:
    enabled: true

management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "info", "hystrix.stream"]
      base-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      registerWithEureka: true
