spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACTHTML5
    encoding: utf-8
    servlet:
      content-type: text/html

server:
  port: 8766

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      registerWithEureka: true
